name: drupal-11-dev
recipe: drupal11
config:
  site: drupal-11-dev
  webroot: web
  php: '8.3'
  # Set xdebug to off by default. Enable it with lando xdebug.
  xdebug: false
  database: mysql:8.0
  config:
    php: lando/configs/php/php.ini
services:
  appserver:
    build_as_root:
      # Create error logs.
      - mkdir -p /app/lando/logs
      - rm -f /app/lando/logs/php_errors.log
      - touch /app/lando/logs/php_errors.log
      - rm -f /app/lando/logs/xdebug.log
      - touch /app/lando/logs/xdebug.log
      # Create custom Drush config to override PHP memory_limit from php.ini.
      - mkdir -p ~/.drush
      - cp /app/lando/configs/drush/drush.ini ~/.drush/drush.ini
      - mkdir -p /etc/drush
      - cp /app/lando/configs/drush/drush.ini /etc/drush/drush.ini
      # Install Nano for debugging purposes (You can use nano after running lando ssh to enter container).
      - mkdir -p /var/lib/apt/lists/partial
      - apt-get update && apt install nano
      # Install jq for parsing $LANDO_INFO var.
      - apt-get -y install jq
      # Start developer off with reasonable local Drupal settings.
      - cp /app/lando/configs/drupal/settings.local.php /app/web/sites/default/settings.local.php
      - cp /app/lando/configs/drupal/development.services.yml /app/web/sites/development.services.yml
    overrides:
      environment:
        # PHPUnit configuration. Sometimes the configuration in phpunit.xml is ignored.
        SIMPLETEST_BASE_URL: "http://drupal-11-dev.lndo.site"
        SIMPLETEST_DB: "mysql://drupal:drupal@database/drupal"
        # Note the URL here must correspond to the name of the service.
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"w3c":false, "args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://selenium-chrome:4444/wd/hub"]'
        # Behat configuration.
        BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "https://drupal-11-dev.lndo.site/"}, "Drupal\\DrupalExtension" : {"drush" : { "root": "/app/web" }}}}'
        # Support debugging Drush with Xdebug.
        PHP_IDE_CONFIG: "serverName=appserver"
        DRUSH_OPTIONS_URI: "https://drupal-11-dev.lndo.site/"
        # This is apparently necessary to overwrite the default Xdebug 3.0
        # config so that our config in /lando/configs/php/php.ini is used.
        XDEBUG_MODE:
  database:
    portforward: 32816
    creds:
      user: drupal
      password: drupal
      database: drupal
  # Selenium Chrome for Behat tests.
  # Feel free to delete if not using Behat.
  selenium-chrome:
    type: compose
    app_mount: false
    services:
      image: seleniarm/standalone-chromium:101.0-20220429
      environment:
        TZ: America/Los_Angeles
        START_XVBF: "false"
      volumes:
        - /dev/shm:/dev/shm
        - ./tests/behat/media:/media:cached
      command: /opt/bin/entry_point.sh
events:
  post-db-import:
    - appserver: /app/lando/scripts/helpers/post-db-import.sh
tooling:
  # Override Drush to run with no memory limit and use version installed by Composer instead of packaged with Lando.
  drush:
    service: appserver
    description: Runs Drush commands
    cmd: php -d memory_limit=-1 -d max_execution_time=-1 /app/vendor/bin/drush
  db-import <file>:
    service: :host
    user: root
    description: Imports a dump file from your local machine into the database service
    cmd:
      - /app/lando/scripts/db-import.sh
  drupal-reinstall:
    service: appserver
    description: DROPs the current database, runs composer install, drush site:install, database updates, config import, deploy hooks and clears caches
    cmd:
      - /app/lando/scripts/drupal-reinstall.sh
  drupal-reset:
    service: appserver
    description: KEEPs the current database, runs composer install, database updates, config import, deploy hooks and clears caches
    cmd:
      - /app/lando/scripts/drupal-reset.sh
  drupal-search-services <string>:
    service: appserver
    description: Searches (greps) Drupal container service names by string
    cmd:
      - /app/lando/scripts/drupal-search-services.sh
  drupal-search-routes <string>:
    service: appserver
    description: Searches (greps) Drupal route names by string
    cmd:
      - /app/lando/scripts/drupal-search-routes.sh
  xdebug [mode | "on" | "off"]:
    description: Starts or stops Xdebug
    cmd:
      - appserver: /app/lando/scripts/xdebug.sh
    user: root
  logs-php:
    service: appserver
    description: Displays and tails PHP error logs
    cmd: tail -f /app/lando/logs/php_errors.log
  logs-xdebug:
    service: appserver
    description: Displays and tails Xdebug logs
    cmd: tail -f /app/lando/logs/xdebug.log
  logs-drupal:
    service: appserver
    description: Displays and tails Drupal logs using Drush
    cmd:
      - drush wt --extended
  php-cs:
    service: appserver
    description: Runs PHP_CodeSniffer on custom modules and themes
    cmd:
      - /app/lando/scripts/php-cs.sh
  twig-cs:
    service: appserver
    description: Runs Twig-CS-Fixer on custom themes and modules
    cmd:
      - /app/lando/scripts/twig-cs.sh
  phpunit <path_to_test>:
    service: appserver
    cmd:
      - /app/lando/scripts/phpunit.sh
  behat [command]:
    service: appserver
    description: Runs Behat CLI commands or all tests
    cmd:
      - /app/lando/scripts/behat.sh
  behat-search-steps <string>:
    service: appserver
    description: Searches (greps) Behat step definitions for string
    cmd:
      - /app/lando/scripts/behat-search-steps.sh
  drupal-create-users:
    service: appserver
    description: Creates Drupal user accounts for testing/development purposes
    cmd:
      - /app/lando/scripts/drupal-create-users.sh
  drupal-status:
    service: appserver
    description: Runs drush status and drush config-status
    cmd:
      - /app/lando/scripts/drupal-status.sh
